import json
import tempfile
import unittest
from pathlib import Path

from depshieldx.npm_lockfiles import parse_lockfile, parse_package_lock_json, parse_pnpm_lock_yaml, parse_yarn_lock

PACKAGE_LOCK_JSON_SAMPLE = {
    "name": "sample-app",
    "version": "1.0.0",
    "lockfileVersion": 3,
    "requires": True,
    "packages": {
        "": {"name": "sample-app", "version": "1.0.0", "dependencies": {"left-pad": "^1.3.0"}},
        "node_modules/left-pad": {
            "version": "1.3.0",
            "resolved": "https://registry.npmjs.org/left-pad/-/left-pad-1.3.0.tgz",
            "integrity": "sha512-XI5MPzVNApjAyhQzphX8BkmKsKUxD4LdyK24iZeQGinBN9yTQT3bFlCBy/aVx2HrNcqQGsdot8ghrjyrvMCoEA==",
        },
        "node_modules/@babel/core": {
            "version": "8.0.1",
            "resolved": "https://registry.npmjs.org/@babel/core/-/core-8.0.1.tgz",
            "integrity": "sha512-5FgxM4dLQpMJHSiVATk8foW263dVHQHBVpXYiimNECVWG01f4nFyEbQixeT6Mwvg7TayREJ2gpKl3o2RoMdnqw==",
        },
    },
}


class PackageLockJsonParserTests(unittest.TestCase):
    def test_parses_scoped_and_plain_entries_and_skips_root(self):
        with tempfile.TemporaryDirectory() as temp_dir:
            path = Path(temp_dir) / "package-lock.json"
            path.write_text(json.dumps(PACKAGE_LOCK_JSON_SAMPLE), encoding="utf-8")
            resolved = parse_package_lock_json(path)

        self.assertEqual(resolved["left-pad"], "1.3.0")
        self.assertEqual(resolved["@babel/core"], "8.0.1")
        self.assertEqual(len(resolved), 2)

    def test_rejects_lockfile_version_1_without_packages_key(self):
        with tempfile.TemporaryDirectory() as temp_dir:
            path = Path(temp_dir) / "package-lock.json"
            path.write_text(json.dumps({"lockfileVersion": 1, "dependencies": {}}), encoding="utf-8")
            with self.assertRaises(ValueError):
                parse_package_lock_json(path)

# Snippets below match the real format captured from actual npm 11 / yarn 1.22 / pnpm 9
# output during development -- see final-plan.md Phase 1. Trimmed to a few packages,
# including a scoped one and (for yarn) a multi-spec header, since those are the
# trickiest cases to parse correctly.

YARN_LOCK_SAMPLE = """\
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


"@babel/helper-validator-identifier@^8.0.0", "@babel/helper-validator-identifier@^8.0.4":
  version "8.0.4"
  resolved "https://registry.yarnpkg.com/@babel/helper-validator-identifier/-/helper-validator-identifier-8.0.4.tgz#60e427a9be7a101af52f14588def2dad8a9f9881"
  integrity sha512-4wFaiLd0bVo4cIoTXI3zKI038NIWE/cr3jvBjejOVYVxV/m8Ltav1USiGzG1fmS5J2RhgEOgXNNK46cRPnRsrg==

chalk@^6.0.0:
  version "6.0.0"
  resolved "https://registry.yarnpkg.com/chalk/-/chalk-6.0.0.tgz#a3bae843bc8454f41ef66ef3fd584dcf34dd805d"
  integrity sha512-2uNTXIuTTxk7ciZgAU1BQcgnchcG0xXnrs6jzkQfj9SsRa9M2s5zE8WT96hS6KmG4MzWHSrvH43DF1m4XRkrFg==

left-pad@^1.3.0:
  version "1.3.0"
  resolved "https://registry.yarnpkg.com/left-pad/-/left-pad-1.3.0.tgz#5b8a3a7765dfe001261dde915589e782f8c94d1e"
  integrity sha512-XI5MPzVNApjAyhQzphX8BkmKsKUxD4LdyK24iZeQGinBN9yTQT3bFlCBy/aVx2HrNcqQGsdot8ghrjyrvMCoEA==
"""

PNPM_LOCK_YAML_SAMPLE = """\
lockfileVersion: '9.0'

settings:
  autoInstallPeers: true
  excludeLinksFromLockfile: false

importers:
  .:
    dependencies:
      left-pad:
        specifier: ^1.3.0
        version: 1.3.0

packages:
  '@babel/core@8.0.1':
    resolution: {integrity: sha512-5FgxM4dLQpMJHSiVATk8foW263dVHQHBVpXYiimNECVWG01f4nFyEbQixeT6Mwvg7TayREJ2gpKl3o2RoMdnqw==}
    engines: {node: ^22.18.0 || >=24.11.0}

  left-pad@1.3.0:
    resolution: {integrity: sha512-XI5MPzVNApjAyhQzphX8BkmKsKUxD4LdyK24iZeQGinBN9yTQT3bFlCBy/aVx2HrNcqQGsdot8ghrjyrvMCoEA==}
"""


class YarnLockParserTests(unittest.TestCase):
    def test_parses_scoped_multi_spec_and_plain_entries(self):
        with tempfile.TemporaryDirectory() as temp_dir:
            path = Path(temp_dir) / "yarn.lock"
            path.write_text(YARN_LOCK_SAMPLE, encoding="utf-8")
            resolved = parse_yarn_lock(path)

        self.assertEqual(resolved["chalk"], "6.0.0")
        self.assertEqual(resolved["left-pad"], "1.3.0")
        self.assertEqual(resolved["@babel/helper-validator-identifier"], "8.0.4")
        self.assertEqual(len(resolved), 3)


class PnpmLockYamlParserTests(unittest.TestCase):
    def test_parses_scoped_and_plain_entries(self):
        with tempfile.TemporaryDirectory() as temp_dir:
            path = Path(temp_dir) / "pnpm-lock.yaml"
            path.write_text(PNPM_LOCK_YAML_SAMPLE, encoding="utf-8")
            resolved = parse_pnpm_lock_yaml(path)

        self.assertEqual(resolved["left-pad"], "1.3.0")
        self.assertEqual(resolved["@babel/core"], "8.0.1")
        self.assertEqual(len(resolved), 2)


class ParseLockfileDispatchTests(unittest.TestCase):
    def test_dispatches_by_filename(self):
        with tempfile.TemporaryDirectory() as temp_dir:
            path = Path(temp_dir) / "yarn.lock"
            path.write_text(YARN_LOCK_SAMPLE, encoding="utf-8")
            resolved = parse_lockfile(path)

        self.assertEqual(resolved["left-pad"], "1.3.0")

    def test_rejects_unsupported_lockfile_name(self):
        with tempfile.TemporaryDirectory() as temp_dir:
            path = Path(temp_dir) / "composer.lock"
            path.write_text("{}", encoding="utf-8")
            with self.assertRaises(ValueError):
                parse_lockfile(path)


if __name__ == "__main__":
    unittest.main()
