import tempfile
import unittest
from pathlib import Path
from unittest.mock import patch

import pytest

from depshieldx.ecosystems import CARGO_ECOSYSTEM

# A minimal, real-shaped Cargo.lock (lockfile version 4), trimmed from
# ripgrep's actual Cargo.lock during development -- see
# test_cargo_lockfiles.py for the fuller fixture and its provenance.
SAMPLE_CARGO_LOCK = """\
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "memchr"
version = "2.7.6"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "63dd52e42f7e35d34b3d9b17f0a44b1937fdc03cbfd0192fc85e19c6e33ce658"

[[package]]
name = "aho-corasick"
version = "1.1.5"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "c982642fa9e8606056828ee9a8505737230110bb1099153c79efe865c59d12ba"
dependencies = [
 "memchr",
]
"""


class CargoEcosystemResolveTests(unittest.TestCase):
    def test_resolve_from_cargo_lock(self):
        with tempfile.TemporaryDirectory() as temp_dir:
            lockfile = Path(temp_dir) / "Cargo.lock"
            lockfile.write_text(SAMPLE_CARGO_LOCK, encoding="utf-8")

            resolution = CARGO_ECOSYSTEM.resolve([], [str(lockfile)], str(lockfile), source_type="lockfile")

        self.assertTrue(resolution.resolution_succeeded)
        self.assertEqual(resolution.resolved_versions["memchr"], "2.7.6")
        self.assertEqual(resolution.resolved_versions["aho-corasick"], "1.1.5")
        self.assertIn("memchr", resolution.packages)

    def test_resolve_reports_error_for_missing_lockfile_target(self):
        resolution = CARGO_ECOSYSTEM.resolve([], [], "unused", source_type="package")

        self.assertFalse(resolution.resolution_succeeded)
        self.assertIn("Cargo.lock", resolution.resolution_error)

    def test_resolve_reports_error_for_unparseable_lockfile(self):
        with tempfile.TemporaryDirectory() as temp_dir:
            lockfile = Path(temp_dir) / "Cargo.lock"
            lockfile.write_text("not valid [[[ toml", encoding="utf-8")

            resolution = CARGO_ECOSYSTEM.resolve([], [str(lockfile)], str(lockfile), source_type="lockfile")

        self.assertFalse(resolution.resolution_succeeded)
        self.assertIsNotNone(resolution.resolution_error)


class CargoAdHocResolveTests(unittest.TestCase):
    def test_resolve_reports_error_for_missing_package_targets(self):
        resolution = CARGO_ECOSYSTEM.resolve([], [], "unused", source_type="package")

        self.assertFalse(resolution.resolution_succeeded)

    @patch("depshieldx.ecosystems.CargoEcosystem._resolve_via_cargo_add")
    def test_resolve_single_crate_uses_cargo_add(self, mock_resolve):
        mock_resolve.return_value = {"serde": "1.0.219"}

        resolution = CARGO_ECOSYSTEM.resolve([], ["serde"], "serde", source_type="package")

        mock_resolve.assert_called_once_with(["serde"])
        self.assertTrue(resolution.resolution_succeeded)
        self.assertEqual(resolution.packages, ["serde"])
        self.assertEqual(resolution.resolved_versions, {"serde": "1.0.219"})
        self.assertEqual(resolution.source_type, "package")

    @patch("depshieldx.ecosystems.CargoEcosystem._resolve_via_cargo_add")
    def test_resolve_multiple_crates_uses_cargo_add(self, mock_resolve):
        mock_resolve.return_value = {"serde": "1.0.219", "anyhow": "1.0.104"}

        resolution = CARGO_ECOSYSTEM.resolve([], ["serde", "anyhow"], "serde, anyhow", source_type="packages")

        mock_resolve.assert_called_once_with(["serde", "anyhow"])
        self.assertTrue(resolution.resolution_succeeded)
        self.assertCountEqual(resolution.packages, ["serde", "anyhow"])

    @patch("depshieldx.ecosystems.CargoEcosystem._resolve_via_cargo_add")
    def test_resolve_reports_registry_failure(self, mock_resolve):
        mock_resolve.side_effect = RuntimeError(
            "cargo could not resolve does-not-exist-xyz: error: the crate `does-not-exist-xyz` could not be found in registry index."
        )

        resolution = CARGO_ECOSYSTEM.resolve([], ["does-not-exist-xyz"], "does-not-exist-xyz", source_type="package")

        self.assertFalse(resolution.resolution_succeeded)
        self.assertIn("does-not-exist-xyz", resolution.resolution_error)


@pytest.mark.live
class CargoEcosystemLiveRegistryTests(unittest.TestCase):
    """Hits the real crates.io registry. Marked live -- excluded from the
    default CI run (`pytest -m "not live"`) since it depends on a
    third-party service's availability and data, unlike the rest of this
    suite which mocks network calls."""

    def test_check_provenance_reports_real_structural_signals(self):
        result = CARGO_ECOSYSTEM.check_provenance({"serde": "1.0.219"})

        self.assertFalse(result["block"])
        detail = result["details"][0]
        self.assertEqual(detail["package"], "serde")
        self.assertFalse(detail["signals"]["has_trustpub_data"])
        self.assertFalse(detail["signals"]["verification_available"])

    def test_selected_artifact_entries_and_fetch_artifact_round_trip(self):
        from depshieldx.resolver import ResolutionResult

        resolution = ResolutionResult(
            packages=["serde"],
            install_target="serde@1.0.219",
            resolved_versions={"serde": "1.0.219"},
        )
        entries = CARGO_ECOSYSTEM.selected_artifact_entries(resolution)
        self.assertEqual(len(entries), 1)
        package_name, version, artifact = entries[0]
        self.assertEqual(package_name, "serde")
        self.assertEqual(version, "1.0.219")
        self.assertTrue(artifact["url"].endswith("/download"))
        self.assertEqual(len(artifact["checksum"]), 64)

        with tempfile.TemporaryDirectory() as temp_dir:
            destination = CARGO_ECOSYSTEM.fetch_artifact(artifact, Path(temp_dir))
            self.assertTrue(destination.exists())
            self.assertGreater(destination.stat().st_size, 0)


class CargoHostInstallCommandTests(unittest.TestCase):
    """host_install_command must pin every resolved package (direct AND
    transitive) to its exact scanned version, not just the requested
    targets. Unlike npm (whose installer respects an existing lockfile and
    only needs the top-level target pinned), a fresh `cargo add` run has no
    Cargo.lock to consult yet -- pinning only the top-level crate would let
    cargo's own resolver pick transitive versions independently at install
    time, which could drift from what was scanned."""

    def _resolution(self, source_type, requested_targets, resolved_versions):
        from depshieldx.resolver import ResolutionResult

        return ResolutionResult(
            packages=list(resolved_versions.keys()),
            install_target=", ".join(requested_targets),
            resolved_versions=resolved_versions,
            requested_targets=requested_targets,
            source_type=source_type,
        )

    @patch("depshieldx.ecosystems.cargo.shutil.which", return_value="/usr/local/bin/cargo")
    @patch.object(CARGO_ECOSYSTEM, "fetch_artifact")
    @patch.object(CARGO_ECOSYSTEM, "selected_artifact_entries", return_value=[])
    def test_ad_hoc_single_crate_install_is_exact_pinned(self, _mock_entries, _mock_fetch, _mock_which):
        resolution = self._resolution("package", ["serde"], {"serde": "1.0.219"})

        with CARGO_ECOSYSTEM.host_install_command(resolution) as command:
            self.assertEqual(command, ["/usr/local/bin/cargo", "add", "serde@=1.0.219"])

    @patch("depshieldx.ecosystems.cargo.shutil.which", return_value="/usr/local/bin/cargo")
    @patch.object(CARGO_ECOSYSTEM, "fetch_artifact")
    @patch.object(CARGO_ECOSYSTEM, "selected_artifact_entries", return_value=[])
    def test_transitive_dependencies_are_also_pinned(self, _mock_entries, _mock_fetch, _mock_which):
        # Only "serde" was requested, but its transitive dep "serde_derive"
        # is also in resolved_versions -- both must be pinned, not just the
        # requested target (see class docstring for why).
        resolution = self._resolution(
            "package", ["serde"], {"serde": "1.0.219", "serde_derive": "1.0.219"}
        )

        with CARGO_ECOSYSTEM.host_install_command(resolution) as command:
            self.assertEqual(command[:2], ["/usr/local/bin/cargo", "add"])
            self.assertCountEqual(command[2:], ["serde@=1.0.219", "serde_derive@=1.0.219"])

    @patch("depshieldx.ecosystems.cargo.shutil.which", return_value="/usr/local/bin/cargo")
    @patch.object(CARGO_ECOSYSTEM, "fetch_artifact")
    @patch.object(CARGO_ECOSYSTEM, "selected_artifact_entries", return_value=[])
    def test_lockfile_install_uses_cargo_fetch(self, _mock_entries, _mock_fetch, _mock_which):
        resolution = self._resolution("lockfile", ["Cargo.lock"], {"serde": "1.0.219"})

        with CARGO_ECOSYSTEM.host_install_command(resolution) as command:
            self.assertEqual(command, ["/usr/local/bin/cargo", "fetch", "--locked"])


class CargoDirectDependencyNamesForLockfileTests(unittest.TestCase):
    def test_reads_dependencies_dev_and_build(self):
        with tempfile.TemporaryDirectory() as temp_dir:
            lockfile = Path(temp_dir) / "Cargo.lock"
            lockfile.write_text("", encoding="utf-8")
            (Path(temp_dir) / "Cargo.toml").write_text(
                '[package]\nname = "demo"\nversion = "0.1.0"\n'
                '\n[dependencies]\nserde = "1.0"\n'
                '\n[dev-dependencies]\ncriterion = "0.5"\n'
                '\n[build-dependencies]\ncc = "1.0"\n',
                encoding="utf-8",
            )

            names = CARGO_ECOSYSTEM.direct_dependency_names_for_lockfile(str(lockfile))

        self.assertEqual(set(names), {"serde", "criterion", "cc"})

    def test_excludes_transitive_only_crates(self):
        with tempfile.TemporaryDirectory() as temp_dir:
            lockfile = Path(temp_dir) / "Cargo.lock"
            lockfile.write_text(SAMPLE_CARGO_LOCK, encoding="utf-8")
            (Path(temp_dir) / "Cargo.toml").write_text(
                '[package]\nname = "demo"\nversion = "0.1.0"\n\n[dependencies]\naho-corasick = "1.1"\n',
                encoding="utf-8",
            )

            names = CARGO_ECOSYSTEM.direct_dependency_names_for_lockfile(str(lockfile))

        self.assertEqual(names, ["aho-corasick"])
        self.assertNotIn("memchr", names)

    def test_missing_cargo_toml_raises_clear_error(self):
        with tempfile.TemporaryDirectory() as temp_dir:
            lockfile = Path(temp_dir) / "Cargo.lock"
            lockfile.write_text("", encoding="utf-8")

            with self.assertRaises(RuntimeError) as ctx:
                CARGO_ECOSYSTEM.direct_dependency_names_for_lockfile(str(lockfile))

        self.assertIn("no Cargo.toml found", str(ctx.exception))


class CargoToolResolutionTests(unittest.TestCase):
    @patch("depshieldx.ecosystems.cargo.shutil.which", return_value="/usr/local/bin/cargo")
    def test_install_command_uses_resolved_path(self, mock_which):
        command = CARGO_ECOSYSTEM.install_command([])

        mock_which.assert_called_with("cargo")
        self.assertEqual(command, ["/usr/local/bin/cargo", "fetch", "--locked"])

    @patch("depshieldx.ecosystems.cargo.shutil.which", return_value="/usr/local/bin/cargo")
    def test_uninstall_command_uses_resolved_path(self, _mock_which):
        command = CARGO_ECOSYSTEM.uninstall_command(["serde"])

        self.assertEqual(command, ["/usr/local/bin/cargo", "remove", "serde"])

    @patch("depshieldx.ecosystems.cargo.shutil.which", return_value=None)
    def test_raises_clear_error_when_cargo_not_on_path(self, _mock_which):
        with self.assertRaises(RuntimeError):
            CARGO_ECOSYSTEM.install_command([])


class CargoArtifactEntriesTests(unittest.TestCase):
    """selected_artifact_entries must skip resolved names that aren't real
    crates.io-hosted packages (path/git/workspace-member dependencies,
    confirmed to have no checksum in a real Cargo.lock -- see
    test_cargo_lockfiles.py) rather than raise."""

    @patch("depshieldx.ecosystems.cargo.fetch_version_metadata")
    def test_skips_entries_missing_checksum_or_dl_path(self, mock_fetch):
        from depshieldx.resolver import ResolutionResult

        mock_fetch.side_effect = [
            {"version": {"num": "1.0.0", "checksum": "abc", "dl_path": "/api/v1/crates/pkg/1.0.0/download"}},
            {"version": {"num": "0.1.0", "checksum": None, "dl_path": None}},
        ]
        resolution = ResolutionResult(
            packages=["pkg", "workspace-member"],
            install_target="unused",
            resolved_versions={"pkg": "1.0.0", "workspace-member": "0.1.0"},
        )

        entries = CARGO_ECOSYSTEM.selected_artifact_entries(resolution)

        self.assertEqual(len(entries), 1)
        self.assertEqual(entries[0][0], "pkg")

    @patch("depshieldx.ecosystems.cargo.fetch_version_metadata")
    def test_skips_entries_that_404(self, mock_fetch):
        import requests

        from depshieldx.resolver import ResolutionResult

        response = requests.Response()
        response.status_code = 404
        mock_fetch.side_effect = requests.exceptions.HTTPError(response=response)
        resolution = ResolutionResult(
            packages=["git-dep"],
            install_target="unused",
            resolved_versions={"git-dep": "0.1.0"},
        )

        entries = CARGO_ECOSYSTEM.selected_artifact_entries(resolution)

        self.assertEqual(entries, [])


if __name__ == "__main__":
    unittest.main()
