import tempfile
import unittest
from pathlib import Path

from depshieldx.ecosystems.cargo.lockfiles import parse_cargo_lock

# Snippets below are trimmed but real -- captured from ripgrep's actual
# Cargo.lock (https://github.com/BurntSushi/ripgrep/blob/master/Cargo.lock,
# lockfile version 4) during development, not hand-written from memory.
# Includes a real duplicate-crate-name-at-two-versions case ("syn") and a
# real workspace-member entry with neither "source" nor "checksum" ("grep").

CARGO_LOCK_SAMPLE = """\
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "aho-corasick"
version = "1.1.5"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "c982642fa9e8606056828ee9a8505737230110bb1099153c79efe865c59d12ba"
dependencies = [
 "memchr",
]

[[package]]
name = "grep"
version = "0.4.1"
dependencies = [
 "grep-cli",
 "grep-matcher",
]

[[package]]
name = "memchr"
version = "2.7.6"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "63dd52e42f7e35d34b3d9b17f0a44b1937fdc03cbfd0192fc85e19c6e33ce658"

[[package]]
name = "syn"
version = "2.0.119"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "872831b642d1a07999a962a351ed35b955ea2cfc8f3862091e2a240a84f17297"
dependencies = [
 "proc-macro2",
 "quote",
]

[[package]]
name = "syn"
version = "3.0.3"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "53e9bae58849f64dfa4f5d5ae372c8341f7305f82a3868709269343628b659a3"
dependencies = [
 "proc-macro2",
 "quote",
]
"""


class ParseCargoLockTests(unittest.TestCase):
    def test_parses_plain_entries(self):
        with tempfile.TemporaryDirectory() as temp_dir:
            path = Path(temp_dir) / "Cargo.lock"
            path.write_text(CARGO_LOCK_SAMPLE, encoding="utf-8")
            resolved = parse_cargo_lock(path)

        self.assertEqual(resolved["aho-corasick"], "1.1.5")
        self.assertEqual(resolved["memchr"], "2.7.6")

    def test_duplicate_crate_name_at_two_versions_keeps_newest(self):
        # Real, common Cargo situation: two different dependencies pin
        # different major versions of the same crate ("syn" 2.x and 3.x
        # both present) -- confirmed directly against ripgrep's real
        # Cargo.lock, which has exactly this. A plain {name: version} map
        # can't represent both at once; the documented tie-break is
        # newest-wins.
        with tempfile.TemporaryDirectory() as temp_dir:
            path = Path(temp_dir) / "Cargo.lock"
            path.write_text(CARGO_LOCK_SAMPLE, encoding="utf-8")
            resolved = parse_cargo_lock(path)

        self.assertEqual(resolved["syn"], "3.0.3")

    def test_workspace_member_without_checksum_or_source_is_still_captured(self):
        # Real workspace-member crates (part of the same repo, not
        # crates.io-hosted) have neither a "source" nor a "checksum" field
        # -- confirmed directly against ripgrep's own "grep" sub-crate.
        # parse_cargo_lock() still returns name/version for these (there's
        # simply nothing to fetch/verify for them downstream).
        with tempfile.TemporaryDirectory() as temp_dir:
            path = Path(temp_dir) / "Cargo.lock"
            path.write_text(CARGO_LOCK_SAMPLE, encoding="utf-8")
            resolved = parse_cargo_lock(path)

        self.assertEqual(resolved["grep"], "0.4.1")

    def test_entries_missing_name_or_version_are_skipped(self):
        with tempfile.TemporaryDirectory() as temp_dir:
            path = Path(temp_dir) / "Cargo.lock"
            path.write_text('version = 4\n\n[[package]]\nname = "onlyname"\n', encoding="utf-8")
            resolved = parse_cargo_lock(path)

        self.assertEqual(resolved, {})


if __name__ == "__main__":
    unittest.main()
