import tempfile
import unittest
from pathlib import Path
from unittest.mock import patch

import pytest
from click.testing import CliRunner

from depshieldx.cli import cli
from depshieldx.cli.engine import _load_cli_input

SAMPLE_CARGO_LOCK = """\
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "left-pad"
version = "1.3.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "0000000000000000000000000000000000000000000000000000000000000000"
"""


class CliCargoDispatchTests(unittest.TestCase):
    """Proves the CLI actually routes cargo lockfile/bare-name input to
    CargoEcosystem end to end, mirroring test_cli_npm_dispatch.py's
    coverage for npm. The real-registry scan test is marked live (real
    resolution against crates.io); the rest are offline."""

    @pytest.mark.live
    def test_scan_bare_package_with_ecosystem_cargo_flag(self):
        runner = CliRunner()
        result = runner.invoke(cli, ["scan", "serde", "--ecosystem", "cargo", "--fast", "--output", "json"])

        self.assertEqual(result.exit_code, 0, result.output)
        import json

        payload = json.loads(result.stdout)
        self.assertEqual(payload["ecosystem"], "cargo")
        self.assertEqual(payload["resolution"]["source_type"], "package")
        self.assertIn("serde", payload["resolution"]["resolved_versions"])

    def test_scan_with_cargo_lockfile_reports_cargo_ecosystem(self):
        with tempfile.TemporaryDirectory() as temp_dir:
            lockfile = Path(temp_dir) / "Cargo.lock"
            lockfile.write_text(SAMPLE_CARGO_LOCK, encoding="utf-8")

            with patch("depshieldx.cli.engine._run_fast_checks") as mock_checks:
                mock_checks.return_value = (
                    {"block": False, "reason": None, "warnings": [], "infos": []},
                    {"block": False, "reason": None, "warnings": [], "infos": [], "threat_intelligence": {}},
                )
                runner = CliRunner()
                result = runner.invoke(
                    cli, ["scan", "--lockfile", str(lockfile), "--fast", "--output", "json"]
                )

        self.assertEqual(result.exit_code, 0, result.output)
        import json

        payload = json.loads(result.stdout)
        self.assertEqual(payload["ecosystem"], "cargo")
        self.assertEqual(payload["resolution"]["resolved_versions"]["left-pad"], "1.3.0")

    def test_load_cli_input_honors_ecosystem_cargo_flag(self):
        input_source = _load_cli_input(("serde",), ecosystem="cargo")

        self.assertEqual(input_source.ecosystem, "cargo")

    def test_install_rejects_invalid_ecosystem_choice(self):
        runner = CliRunner()
        result = runner.invoke(cli, ["install", "serde", "--ecosystem", "gomod"])

        self.assertNotEqual(result.exit_code, 0)
        self.assertIn("Invalid value", result.output)

    def test_uninstall_cargo_lockfile_without_cargo_toml_fails_clearly(self):
        with tempfile.TemporaryDirectory() as temp_dir:
            lockfile = Path(temp_dir) / "Cargo.lock"
            lockfile.write_text(SAMPLE_CARGO_LOCK, encoding="utf-8")

            runner = CliRunner()
            result = runner.invoke(cli, ["uninstall", "--lockfile", str(lockfile)])

        self.assertNotEqual(result.exit_code, 0)
        self.assertIn("no Cargo.toml found", str(result.output) + str(result.exception))

    @patch("depshieldx.cli.commands.uninstall._run_cli_command")
    def test_uninstall_cargo_lockfile_uses_direct_dependencies_from_cargo_toml(self, mock_run_cli):
        with tempfile.TemporaryDirectory() as temp_dir:
            lockfile = Path(temp_dir) / "Cargo.lock"
            lockfile.write_text(SAMPLE_CARGO_LOCK, encoding="utf-8")
            (Path(temp_dir) / "Cargo.toml").write_text(
                '[package]\nname = "demo"\nversion = "0.1.0"\n\n[dependencies]\nleft-pad = "1.3.0"\n',
                encoding="utf-8",
            )

            with patch("depshieldx.ecosystems.cargo.shutil.which", return_value="/usr/local/bin/cargo"):
                runner = CliRunner()
                result = runner.invoke(cli, ["uninstall", "--lockfile", str(lockfile)])

        self.assertEqual(result.exit_code, 0, result.output)
        uninstall_command = mock_run_cli.call_args.args[0]
        self.assertEqual(uninstall_command, ["/usr/local/bin/cargo", "remove", "left-pad"])

    @patch("depshieldx.cli.commands.uninstall._run_cli_command")
    def test_uninstall_cargo_bare_package_names_with_ecosystem_flag(self, mock_run_cli):
        with patch("depshieldx.ecosystems.cargo.shutil.which", return_value="/usr/local/bin/cargo"):
            runner = CliRunner()
            result = runner.invoke(cli, ["uninstall", "serde", "anyhow", "--ecosystem", "cargo"])

        self.assertEqual(result.exit_code, 0, result.output)
        uninstall_command = mock_run_cli.call_args.args[0]
        self.assertEqual(uninstall_command[:2], ["/usr/local/bin/cargo", "remove"])
        self.assertCountEqual(uninstall_command[2:], ["serde", "anyhow"])


if __name__ == "__main__":
    unittest.main()
